version: "3"
services:  
  mariadb: 
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"  
    environment:
      MARIADB_ROOT_PASSWORD: 'password'    
    volumes:
      - dbdata:/var/lib/mysql      
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - "8888:8080"
volumes:
   dbdata:        

    