version: "3"
services:
  mariadb: 
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 'password'    
    volumes:
      - ~/mariadb:/var/lib/mysql      
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 8888:8080
  backend:
    build: ./
    container_name: backend
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mariadb

# volumes:
#   dbdata:

    